# Generated by Django 5.0.6 on 2024-06-23 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('rooms', models.IntegerField()),
                ('area', models.FloatField()),
                ('price', models.FloatField()),
                ('url', models.URLField()),
            ],
        ),
    ]
