# Generated by Django 5.0.6 on 2024-06-23 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Listing',
            new_name='Offer',
        ),
    ]
