# Generated by Django 5.0.6 on 2024-06-23 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_rename_listing_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='img',
            field=models.URLField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offer',
            name='district',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='offer',
            name='street',
            field=models.CharField(max_length=255),
        ),
    ]
